### ISSUE TITLE
lanes not shown

### ISSUE THREAD

**Issue by tgif73** [Flycars/4LaneRoad#1]
Hello, thank you for sharing the map. This will be very helpful. 
I'm new to Unity so please excuse me for asking silly question. When I load the environment, I don't see the lanes (scene lighting doesn't make any change). I can build it as is, but when launched, the map doesn't show the lanes. Is there anything I need to do? I'm using Unity 2019.3.3f with LGSVL 03/2020 version.

![image](https://user-images.githubusercontent.com/20801061/85083759-877c6800-b187-11ea-98f5-73213d748233.png)

**Comment by daohu527** [comment]
I'm not sure if the version of lgsvl cause this. The map has no light source, because the game has its own light source. When debugging, you can add a light source to see if any texture appears.  

I will check for it later, by the way, how do you use this map ?

**Comment by tgif73** [comment]
We will use this map (as well as other maps) to run simple ADAS/AD simulated scenarios. Thanks.

**Comment by daohu527** [comment]
@tgif73 I have update the map, you can download the build version in baidu pan link which published in readme. If you want a linux version you can build from the source yourself.

**Comment by tgif73** [comment]
@daohu527 Great! It has loaded with all lanes shown. Thank you!
